# Generated by Django 4.0.4 on 2022-06-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('properties', '0002_property_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, to='files.file'),
        ),
    ]
